services:
  sandbox-web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - dvwa
      - bwapp
      - juiceshop
      - webgoat
      - mutillidae
      - vulnerable-wordpress
      - vulnerable-joomla
      - hackazon

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    environment:
      - PHPIDS_ENABLED=false

  bwapp:
    image: raesene/bwapp
    ports:
      - "8082:80"

  juiceshop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"

  webgoat:
    image: webgoat/webgoat-8.0
    ports:
      - "8080:8080"

  mutillidae:
    image: citizenstig/nowasp
    ports:
      - "8083:80"

  vulnerable-wordpress:
    image: wpscanteam/vulnerablewordpress
    ports:
      - "8084:80"

  vulnerable-joomla:
    image: greggm/vulnerable-joomla
    ports:
      - "8085:80"

  hackazon:
    image: citizenstig/hackazon
    ports:
      - "8086:80"
    volumes:
      - hackazon_data:/var/www/html
    entrypoint: /bin/sh -c "chown -R www-data:www-data /var/www/html && /run.sh"


volumes:
  hackazon_data: {}  

networks:
  default:
    name: web-security-sandbox
    driver: bridge
