version: '3.8'

services:
  drupal:
    build: .
    container_name: drupal_865_vuln
    ports:
      - "8088:80"


    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
